config/routes.rb
Rails.application.routes.draw do
  
  devise_for :usuarios
  
  resources :artigos do
    resources :comentarios
  end

  resources :cadastros

  get  'home' => 'home#index'
  root 'home#index'

end

app/models/artigo.rb
class Artigo < ActiveRecord::Base
  scope :publicados, -> { where publicar: true }

  belongs_to :usuario
  has_many :comentarios
  
  validates :titulo, :descricao, :usuario, presence: true
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :artigo
  belongs_to :usuario

  validates :artigo, :descricao, presence: true
  validates :descricao, :uniqueness => {:scope => [:artigo_id, :descricao]}
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_usuario!

  def current_user
    current_usuario
  end
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
  before_action :set_artigo, only: [:show, :edit, :update, :destroy]

  # GET /artigos
  # GET /artigos.json
  def index
    @artigos = Artigo.where(usuario:current_usuario)
  end

  # GET /artigos/1
  # GET /artigos/1.json
  def show
  end

  # GET /artigos/new
  def new
    @artigo = Artigo.new
  end

  # GET /artigos/1/edit
  def edit
  end

  # POST /artigos
  # POST /artigos.json
  def create
    @artigo = Artigo.new(artigo_params)
    @artigo.usuario = current_usuario

    respond_to do |format|
      if @artigo.save
        format.html { redirect_to @artigo, notice: 'Artigo was successfully created.' }
        format.json { render :show, status: :created, location: @artigo }
      else
        format.html { render :new }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artigos/1
  # PATCH/PUT /artigos/1.json
  def update
    respond_to do |format|
      if @artigo.update(artigo_params)
        format.html { redirect_to @artigo, notice: 'Artigo was successfully updated.' }
        format.json { render :show, status: :ok, location: @artigo }
      else
        format.html { render :edit }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artigos/1
  # DELETE /artigos/1.json
  def destroy
    @artigo.destroy
    respond_to do |format|
      format.html { redirect_to artigos_url, notice: 'Artigo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artigo
      @artigo = Artigo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artigo_params
      params.require(:artigo).permit(:titulo, :descricao, :publicar)
    end
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]

  # GET /cadastros
  # GET /cadastros.json
  def index
    @cadastros = Usuario.all
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Usuario.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Usuario.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to cadastros_url, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to cadastros_url, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:usuario).permit(:nome, :email)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:destroy]

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario         = Comentario.new(comentario_params)
    @comentario.artigo  = Artigo.find(params[:artigo_id])
    @comentario.usuario = current_usuario

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to home_path }
      else
        format.html { redirect_to home_path }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:artigo_id, :descricao)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /home
  def index
    @artigos = Artigo.includes(:comentarios).publicados
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
  def help_artigo_publicado artigo
    tipo_botao = if artigo.publicar 
      'btn-success'
    else
      'btn-danger'
    end

    button_tag(type: 'button', class:"btn #{tipo_botao} btn-sm") do
      content_tag(:strong, '!!!')
    end
  end
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artigos/_form.html.erb
<%= simple_form_for @artigo do |f| %>
  
  <%= f.input :titulo %>
  <%= f.input :descricao, as: :wysihtml5 %>
  <%= f.input :publicar %>
  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            artigos_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/artigos/edit.html.erb
<%- model_class = Artigo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artigos/index.html.erb
<%- model_class = Artigo -%>
<div class="page-header">
  <h1><%= I18n.t 'activerecord.models_custom.meus_artigos' %></h1>
</div>


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_artigo_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:usuario_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:publicar) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @artigos.each do |artigo| %>
      <tr>
        <td><%= artigo.titulo %></td>
        <td><%=raw artigo.descricao %></td>
        <td><%= artigo.usuario.email.split('@').first %></td>
        <td><%=l artigo.created_at, format: :short %></td>
        <td><%= help_artigo_publicado artigo %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_artigo_path(artigo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artigo_path(artigo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artigos/new.html.erb
<%- model_class = Artigo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artigos/show.html.erb
<%- model_class = Artigo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @artigo.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%=raw @artigo.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:publicar) %>:</strong></dt>
  <dd><%= help_artigo_publicado @artigo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:usuario_id) %>:</strong></dt>
  <dd><%= @artigo.usuario.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              artigos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artigo_path(@artigo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artigo_path(@artigo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/cadastros/_form.html.erb
<%= simple_form_for @cadastro, url: { action: {new: 'create', create: 'create', edit: 'update', update: 'update'}[params[:action].to_sym] } do |f| %>
  
  <%= f.input :nome %>
  <%= f.input :email %>
  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            cadastros_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/cadastros/edit.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cadastros/index.html.erb
<%- model_class = Artigo -%>
<div class="page-header">
  <h1><%= I18n.t 'activerecord.models_custom.cadastro_ususuarios' %></h1>
</div>


<%= link_to t('.new', :default => t("helpers.links.new")), new_cadastro_path, :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cadastros.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%=l usuario.created_at, format: :short %></td>
         <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cadastro_path(usuario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cadastro_path(usuario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cadastros/new.html.erb
<%- model_class = Usuario -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>

app/views/comentarios/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for([artigo, Comentario.new]) do |f| %>
      <%= f.input :descricao %><br>
      <%= f.submit nil, :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<blockquote>  
<h1 style="font-size: 40px">Blog</h1>
  <small class="lead" style="color: #999; font-size: 30px">Blog Blogado!</small>
</blockquote>

<div style="margin-left: 21px;">

  <%@artigos.each do |artigo| %>
    <blockquote>  
      <h1><%=artigo.titulo%></h1>
      <div class="well">  
        <h3><%=raw artigo.descricao%></h3>
      </div>
      <h3 class="pull-right"><small><%=l artigo.created_at, format: :long%> por <%= link_to artigo.usuario.email,'#' %> </small></h3>
      <br clear="all"/>
      <% artigo.comentarios.each do |comentario|%>
        <blockquote>
          <p class="lead"><%=comentario.descricao%></p>
          <footer class="lead" style="font-size: 11px;"><%=l comentario.created_at, format: :long%> por <%= link_to comentario.usuario.email,'#' %></footer>
        </blockquote>
      <% end -%>

      <%= render file: 'comentarios/_form.html', locals:{artigo: artigo} %>
    </blockquote>
    <hr />
    <hr />
  <% end -%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <%= image_tag 'blogger-logo.jpg', size: "24" %>
        </a>
      </div>

      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller].eql?'home'%>"><a href="/">Home</a></li>
        <li class="<%= 'active' if params[:controller].eql?'artigos'%>"><%= link_to Artigo.model_name.human.pluralize , artigos_path %></li>
        <li class="<%= 'active' if params[:controller].eql?'cadastros'%>"><%= link_to Usuario.model_name.human.pluralize , cadastros_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sair', destroy_usuario_session_path, class:'btn', method: :delete%></li>
      </ul>

    </div>
  </nav>
  
  <div class="container-fuild">
    <div class="row-fuild">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
      </div>
    </div><!--/row-->
  </div>

  <div class="container">
    <%= yield %>
  </div>


  <div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title"></h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>


</body>
</html>